Traceback (most recent call last):
  File "/home/pengyu/.local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/software/python-anaconda-2022.05-el8-x86_64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/software/python-anaconda-2022.05-el8-x86_64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/software/python-anaconda-2022.05-el8-x86_64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/software/python-anaconda-2022.05-el8-x86_64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/software/python-anaconda-2022.05-el8-x86_64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/software/python-anaconda-2022.05-el8-x86_64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/software/python-anaconda-2022.05-el8-x86_64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
x_theta=np.load('theta_u_0.05.npy')
x_gamma=np.load('gamma_u_0.05.npy')

x_no_u = np.load('no_u.npy')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [0;32mIn [12][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m x_theta[38;5;241m=[39m[43mnp[49m[38;5;241;43m.[39;49m[43mload[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mtheta_u_0.05.npy[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      2[0m x_gamma[38;5;241m=[39mnp[38;5;241m.[39mload([38;5;124m'[39m[38;5;124mgamma_u_0.05.npy[39m[38;5;124m'[39m)
[1;32m      4[0m x_no_u [38;5;241m=[39m np[38;5;241m.[39mload([38;5;124m'[39m[38;5;124mno_u.npy[39m[38;5;124m'[39m)

File [0;32m~/.local/lib/python3.9/site-packages/numpy/lib/npyio.py:427[0m, in [0;36mload[0;34m(file, mmap_mode, allow_pickle, fix_imports, encoding, max_header_size)[0m
[1;32m    425[0m     own_fid [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[1;32m    426[0m [38;5;28;01melse[39;00m:
[0;32m--> 427[0m     fid [38;5;241m=[39m stack[38;5;241m.[39menter_context([38;5;28;43mopen[39;49m[43m([49m[43mos_fspath[49m[43m([49m[43mfile[49m[43m)[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m"[39;49m[43m)[49m)
[1;32m    428[0m     own_fid [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m    430[0m [38;5;66;03m# Code to distinguish from NumPy binary files and pickles.[39;00m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'theta_u_0.05.npy'
FileNotFoundError: [Errno 2] No such file or directory: 'theta_u_0.05.npy'

